name: Build LaTeX document

permissions:
  contents: write
  discussions: write

on:
  pull_request:
    types:
      - opened
    branches:
      - main
      - multifile
  push:
    branches:
      - main
      - multifile
    tags:
      - 'v*'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Pygmentize setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip" # caching pip dependencies
      - name: Install Pygments requirement
        run: pip install Pygments
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        env:
          working-directory: ./thesis
        with:
          texlive_version: 2024
          latexmk_shell_escape: true
          root_file: thesis.tex
          working_directory: ./thesis
      - uses: actions/upload-artifact@v4
        name: Upload Article as artifact
        # https://github.com/actions/upload-artifact?tab=readme-ov-file#inputs
        with:
          name: Thesis
          # -${{ github.ref_type }}-${{github.ref_name}}
          path: ./thesis/thesis.pdf
          if-no-files-found: error
      - name: Compile Subfiles
        uses: xu-cheng/latex-action@v3
        env:
          working-directory: ./parts
        with:
          texlive_version: 2024
          latexmk_shell_escape: true
          root_file: |
            *.tex
          working_directory: ./parts
      - uses: actions/upload-artifact@v4
        name: Upload Subfiles as artifact
        # https://github.com/actions/upload-artifact?tab=readme-ov-file#inputs
        with:
          name: Subfiles
          path: ./parts/*.pdf
          if-no-files-found: error
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ./thesis/thesis.pdf
            ./parts/*.pdf
          draft: false
          fail_on_unmatched_files: true
